name:                hs-stack-graphs
version:             0.1.0.0
github:              "githubuser/hs-stack-graphs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-stack-graphs#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- vector >= 0.12 && <0.13
- time
- optics
- generic-optics

default-extensions:
- ImportQualifiedPost
- DerivingStrategies
- DeriveGeneric
- DeriveAnyClass
- CApiFFI
- GeneralizedNewtypeDeriving

ghc-options: "-optc=-Wno-nullability-completeness -optc=-Wno-expansion-to-defined"

library:
  source-dirs: src
  extra-libraries: stack_graphs
  c-sources: cbits/hs_stack_graphs.c
  include-dirs:         include
  cc-options: -Wno-nullability-completeness
  dependencies:
    - derive-storable


benchmarks:
  hs-stack-graphs-bench:
    source-dirs: bench
    main: Main.hs
    dependencies:
      - hs-stack-graphs
      - gauge
      - random

tests:
  hs-stack-graphs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-stack-graphs
    - hedgehog
